name: CI/CD Demo Report

on:
  push:
    branches: [ "main" ]

jobs:
  demo-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 1. Server - Ki·ªÉm tra m√£ ngu·ªìn
      uses: actions/checkout@v4

    - name: 2. Server - Chu·∫©n b·ªã m√¥i tr∆∞·ªùng Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: 3. Backend - C√†i ƒë·∫∑t th∆∞ vi·ªán (Demo)
      run: |
        echo "Dang cai dat thu vien cho Backend..."
        echo "‚úÖ Backend Dependencies Installed!"

    - name: 4. Frontend - Build giao di·ªán (Demo)
      run: |
        echo "Dang build ReactJS..."
        echo "‚úÖ Frontend Build Success!"

    - name: 5. Kich hoat Deploy tu dong
      run: echo "üöÄ Code da san sang. Render se tu dong Deploy ngay lap tuc."
